=== codeaudit/cougaar-util/base/configs/common/ClusterAssets.ldm.dtd
<!ELEMENT clusterassets (prototype*, instance*)>

<!ELEMENT prototype (object)>
<!ATTLIST prototype name CDATA #REQUIRED>

<!ELEMENT instance (schedule)>
<!ATTLIST instance id ID #REQUIRED>
<!ATTLIST instance prototype CDATA #REQUIRED>

<!ELEMENT schedule EMPTY>
<!ATTLIST schedule start CDATA #REQUIRED>
<!ATTLIST schedule end CDATA #REQUIRED>

<!ELEMENT object (property*)>
<!ATTLIST object id ID #REQUIRED>
<!ATTLIST object class CDATA #REQUIRED>

<!ELEMENT field EMPTY>
<!ATTLIST field name ID #REQUIRED>
<!ATTLIST field type CDATA #REQUIRED>
<!ATTLIST field value CDATA #REQUIRED>

<!ELEMENT property (field*)>
<!ATTLIST property id ID #REQUIRED>
<!ATTLIST property class CDATA #REQUIRED>

=== codeaudit/cougaar-util/base/configs/common/VFA-260-F18-SQDN.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE ClusterAssets SYSTEM "ClusterAssets.ldm.dtd" []>

<clusterassets>
  <prototype name="NSN/F18">
    <object class="org.cougaar.glm.ldm.asset.FixedWingAircraftWeapon" id="proto-001">
      <property class="org.cougaar.planning.ldm.asset.TypeIdentificationPG" id="property-001">
	<field value="NSN/F18" type="java.lang.String" name="TypeIdentification"/>
	<field value="F18" type="java.lang.String" name="Nomenclature"/>
      </property>
    </object>
  </prototype>
  <instance prototype="NSN/F18" id="b001">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/F18" id="b002">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/F18" id="b003">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/F18" id="b004">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/F18" id="b005">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/F18" id="b006">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/F18" id="b007">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/F18" id="b008">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/F18" id="b009">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/F18" id="b010">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/F18" id="b011">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/F18" id="b012">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
</clusterassets>

=== codeaudit/cougaar-util/base/configs/common/VRC-30-C2-SQDN.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE ClusterAssets SYSTEM "ClusterAssets.ldm.dtd" []>

<clusterassets>
  <prototype name="NSN/C2">
    <object class="org.cougaar.domain.glm.ldm.asset.FixedWingAircraftWeapon" id="proto-001">
      <property class="org.cougaar.domain.planning.ldm.asset.TypeIdentificationPG" id="property-001">
	<field value="NSN/C2" type="java.lang.String" name="TypeIdentification"/>
	<field value="H60" type="java.lang.String" name="Nomenclature"/>
      </property>
    </object>
  </prototype>
  <instance prototype="NSN/C2" id="a001">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/C2" id="a002">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
</clusterassets>

=== codeaudit/cougaar-util/base/configs/common/VAW-212-E2C-SQDN.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE ClusterAssets SYSTEM "ClusterAssets.ldm.dtd" []>

<clusterassets>
  <prototype name="NSN/E2C">
    <object class="org.cougaar.glm.ldm.asset.FixedWingAircraftWeapon" id="proto-001">
      <property class="org.cougaar.planning.ldm.asset.TypeIdentificationPG" id="property-001">
	<field value="NSN/E2C" type="java.lang.String" name="TypeIdentification"/>
	<field value="H60" type="java.lang.String" name="Nomenclature"/>
      </property>
    </object>
  </prototype>
  <instance prototype="NSN/E2C" id="a001">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/E2C" id="a002">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/E2C" id="a003">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
  <instance prototype="NSN/E2C" id="a004">
    <schedule start="01/01/99" end="12/31/10"/>
  </instance>
</clusterassets>
