=== codeaudit/cougaar-util/base/configs/common/Policy.ldm.dtd
<!ELEMENT Policies (Policy*)>

<!ELEMENT Policy (RuleParam*)>
<!ATTLIST Policy name ID #REQUIRED>
<!ATTLIST Policy type CDATA #REQUIRED>

<!ELEMENT RuleParam (Double|Integer|String|Enumeration|Class)>
<!ATTLIST RuleParam name ID #REQUIRED>

<!ELEMENT Double EMPTY>
<!ATTLIST Double value CDATA #REQUIRED>
<!ATTLIST Double min CDATA #REQUIRED>
<!ATTLIST Double max CDATA #REQUIRED>

<!ELEMENT Integer EMPTY>
<!ATTLIST Integer value CDATA #REQUIRED>
<!ATTLIST Integer min CDATA #REQUIRED>
<!ATTLIST Integer max CDATA #REQUIRED>

<!ELEMENT String EMPTY>
<!ATTLIST String value CDATA #REQUIRED>

<!ELEMENT Enumeration (EnumOption+)>
<!ATTLIST Enumeration value CDATA #REQUIRED>

<!ELEMENT EnumOption EMPTY>
<!ATTLIST EnumOption value CDATA #REQUIRED>


<!ELEMENT Class EMPTY>
<!ATTLIST Class class_type CDATA #REQUIRED>

<!ELEMENT Boolean EMPTY>
<!ATTLIST Boolean value CDATA #REQUIRED>

=== codeaudit/cougaar-util/base/configs/common/InventoryPolicy-THEATER-POL-SUPPLYCO.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<!-- Inventory Policy for THEATER-POL-SUPPLYCO.ldm.xml, et al: Corps-Level Materiel Supply units -->

<Policies>

 <Policy name="BulkPOLInventoryPolicy" type="org.cougaar.glm.plugins.inventory.InventoryPolicy">
    <RuleParam name="ResourceType">
      	<String value ="BulkPOL">
	</String>
    </RuleParam>
    <RuleParam name="DaysOnHand">
	<Integer value="5" min="-1" max="90"> 
	</Integer>
    </RuleParam>
    <RuleParam name="DaysForward">
        <Integer value="10" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="DaysBackward">
        <Integer value="0" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="GoalLevelMultiplier">
        <Double value="5" min="1.0" max="30">
	</Double>
    </RuleParam>
    <RuleParam name="WithdrawSwitchoverDay">
        <Integer value="30" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="RefillSwitchoverDay">
        <Integer value="100" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="TurnOffProjections">
        <Boolean value="false">
        </Boolean>
    </RuleParam>
  </Policy>

 <Policy name="PackagedPOLInventoryPolicy" type="org.cougaar.glm.plugins.inventory.InventoryPolicy">
    <RuleParam name="ResourceType">
      	<String value ="PackagedPOL">
	</String>
    </RuleParam>
    <RuleParam name="DaysOnHand">
	<Integer value="5" min="-1" max="90"> 
	</Integer>
    </RuleParam>
    <RuleParam name="DaysForward">
        <Integer value="5" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="DaysBackward">
        <Integer value="0" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="GoalLevelMultiplier">
        <Double value="2.5" min="1.0" max="30">
	</Double>
    </RuleParam>
    <RuleParam name="WithdrawSwitchoverDay">
        <Integer value="30" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="RefillSwitchoverDay">
        <Integer value="100" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="TurnOffProjections">
        <Boolean value="false">
        </Boolean>
    </RuleParam>
  </Policy>

</Policies>

=== codeaudit/cougaar-util/base/configs/common/InventoryPolicy-ESBN.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<!-- Inventory Policy for FSB, et al: First Level Supply units -->

<Policies>

 <Policy name="ClassISubsistenceInventoryPolicy" type="org.cougaar.domain.glm.plugins.inventory.InventoryPolicy">
    <RuleParam name="ResourceType">
      	<String value ="ClassISubsistence">
	</String>
    </RuleParam>
    <RuleParam name="DaysOnHand">
	<Integer value="1" min="-1" max="90"> 
	</Integer>
    </RuleParam>
    <RuleParam name="DaysForward">
        <Integer value="7" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="DaysBackward">
        <Integer value="0" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="GoalLevelMultiplier">
        <Double value="2" min="1.0" max="30">
	</Double>
    </RuleParam>
    <RuleParam name="WithdrawSwitchoverDay">
        <Integer value="45" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="RefillSwitchoverDay">
        <Integer value="45" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="TurnOffProjections">
        <Boolean value="false">
        </Boolean>
    </RuleParam>
  </Policy>

 <Policy name="ClassVIIIMedicalOnHandPolicy" type="org.cougaar.domain.glm.plugins.inventory.InventoryPolicy">
    <RuleParam name="ResourceType">
      	<String value ="ClassVIIIMedical">
	</String>
    </RuleParam>
    <RuleParam name="DaysOnHand">
	<Integer value="7" min="-1" max="90"> 
	</Integer>
    </RuleParam>
    <RuleParam name="DaysForward">
        <Integer value="30" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="DaysBackward">
        <Integer value="0" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="GoalLevelMultiplier">
        <Double value="2" min="1.0" max="30">
	</Double>
    </RuleParam>
    <RuleParam name="WithdrawSwitchoverDay">
        <Integer value="45" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="RefillSwitchoverDay">
        <Integer value="45" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="TurnOffProjections">
        <Boolean value="false">
        </Boolean>
    </RuleParam>
  </Policy>

 <Policy name="AmmunitionOnHandPolicy" type="org.cougaar.domain.glm.plugins.inventory.InventoryPolicy">
    <RuleParam name="ResourceType">
      	<String value ="Ammunition">
	</String>
    </RuleParam>
    <RuleParam name="DaysOnHand">
	<Integer value="6" min="-1" max="90"> 
	</Integer>
    </RuleParam>
    <RuleParam name="DaysForward">
        <Integer value="7" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="DaysBackward">
        <Integer value="0" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="GoalLevelMultiplier">
        <Double value="2" min="1.0" max="30">
	</Double>
    </RuleParam>
    <RuleParam name="WithdrawSwitchoverDay">
        <Integer value="30" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="RefillSwitchoverDay">
        <Integer value="30" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="TurnOffProjections">
        <Boolean value="false">
        </Boolean>
    </RuleParam>
  </Policy>

 <Policy name="BulkPOLOnHandPolicy" type="org.cougaar.domain.glm.plugins.inventory.InventoryPolicy">
    <RuleParam name="ResourceType">
      	<String value ="BulkPOL">
	</String>
    </RuleParam>
    <RuleParam name="DaysOnHand">
	<Integer value="1" min="-1" max="90"> 
	</Integer>
    </RuleParam>
    <RuleParam name="DaysForward">
        <Integer value="5" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="DaysBackward">
        <Integer value="0" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="GoalLevelMultiplier">
        <Double value="1.1" min="1.0" max="30">
	</Double>
    </RuleParam>
    <RuleParam name="WithdrawSwitchoverDay">
        <Integer value="0" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="RefillSwitchoverDay">
        <Integer value="45" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="TurnOffProjections">
        <Boolean value="false">
        </Boolean>
    </RuleParam>
  </Policy>

 <Policy name="PackagedPOLOnHandPolicy" type="org.cougaar.domain.glm.plugins.inventory.InventoryPolicy">
    <RuleParam name="ResourceType">
      	<String value ="PackagedPOL">
	</String>
    </RuleParam>
    <RuleParam name="DaysOnHand">
	<Integer value="1" min="-1" max="90"> 
	</Integer>
    </RuleParam>
    <RuleParam name="DaysForward">
        <Integer value="5" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="DaysBackward">
        <Integer value="0" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="GoalLevelMultiplier">
        <Double value="1.1" min="1.0" max="30">
	</Double>
    </RuleParam>
    <RuleParam name="WithdrawSwitchoverDay">
        <Integer value="0" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="RefillSwitchoverDay">
        <Integer value="45" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="TurnOffProjections">
        <Boolean value="false">
        </Boolean>
    </RuleParam>
  </Policy>


 <Policy name="ConsumableOnHandPolicy" type="org.cougaar.domain.glm.plugins.inventory.InventoryPolicy">
    <RuleParam name="ResourceType">
      	<String value ="Consumable">
	</String>
    </RuleParam>
    <RuleParam name="DaysOnHand">
	<Integer value="6" min="-1" max="90"> 
	</Integer>
    </RuleParam>
    <RuleParam name="DaysForward">
        <Integer value="7" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="DaysBackward">
        <Integer value="0" min="0" max="30">
	</Integer>
    </RuleParam>
    <RuleParam name="GoalLevelMultiplier">
        <Double value="2" min="1.0" max="30">
	</Double>
    </RuleParam>
    <RuleParam name="WithdrawSwitchoverDay">
        <Integer value="0" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="RefillSwitchoverDay">
        <Integer value="45" min="0" max="300">
        </Integer>
    </RuleParam>
    <RuleParam name="TurnOffProjections">
        <Boolean value="false">
        </Boolean>
    </RuleParam>
  </Policy>

</Policies>

=== codeaudit/cougaar-util/base/configs/minitestconfig/policy.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE Policy SYSTEM "Policy.ldm.dtd" []>

<Policies>

 <Policy name="ShipPolicy" type="org.cougaar.glm.ldm.policy.ShipPolicy">
    <RuleParam name="ShipDays">
	<Integer value="3" min="1" max="10"> 
	</Integer>
    </RuleParam>
    <RuleParam name="ShipMode">
       <Enumeration value="Ground">
	  <EnumOption value="Ground"> </EnumOption>
	  <EnumOption value="Sea"> </EnumOption>
	  <EnumOption value="Air"> </EnumOption>
       </Enumeration>
    </RuleParam>
  </Policy>

 <Policy name="StockageLevelPolicy" type="org.cougaar.glm.ldm.policy.StockageLevelPolicy">
    <RuleParam name="DaysOfSupply">
	<Integer value="7" min="0" max="365"> 
	</Integer>
    </RuleParam>
    <RuleParam name="HostNation">
       <Boolean value="false"> </Boolean>
    </RuleParam>
    <RuleParam name="WarReserves">
       <Boolean value="false"> </Boolean>
    </RuleParam>
    <RuleParam name="PrepositionStock">
       <Boolean value="false"> </Boolean>
    </RuleParam>
  </Policy>
</Policies>
